MVC_Project/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace Final_Project.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public double Price { get; set; }

        public string Image { get; set; }
        public string Description { get; set; }
        public string Quantity { get; set; }
        
        public virtual List<Order_Details>? Order_Details { get; set; }

    }
}

MVC_Project/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Final_Project.Controllers
{
    public class AboutController : Controller
    {
        [HttpGet]
        public IActionResult index()
        {
            return View();
        }
    }
}

MVC_Project/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace Final_Project.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MVC_Project/Controllers/CustomerController.cs
using Final_Project.Models;
using Final_Project.Repository;
using Final_Project.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Final_Project.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CustomerController : Controller
    {

        ICustomerRepository CustomerRepository;
        public CustomerController(ICustomerRepository customer)
        {
            CustomerRepository = customer;

        }
        public IActionResult Index()
        {
            return View(CustomerRepository.GetAll());
        }

        public IActionResult Details(int id)
        {
            return View(CustomerRepository.GetById(id));
        }

        [HttpGet]
        public IActionResult New()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult New(RegisterVM customer)
        {
            if (ModelState.IsValid)
            {
                CustomerRepository.Insert(customer);
                return RedirectToAction("AdminView");
            }
            return View(customer);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Customer customer = CustomerRepository.GetById(id);
            return View(customer);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Customer customer)
        {
            if (ModelState.IsValid)
            {
                CustomerRepository.Update(id, customer);
                return RedirectToAction("AdminView");
            }
            return View(customer);
        }


        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            CustomerRepository.Delete(id);
            return RedirectToAction("AdminView");
        }
        [Authorize(Roles="Admin")]
        public IActionResult AdminView()
        {
            return View(CustomerRepository.GetAll());
        }
    }
}

MVC_Project/Controllers/OrderController.cs
using Final_Project.Models;
using Final_Project.Repository;
using Final_Project.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Nancy.Json;
using Newtonsoft.Json;

namespace Final_Project.Controllers
{
    public class OrderController : Controller
    {
        IProductRepository productRepository;
        IOrderRepository orderRepository;
        ICustomerRepository customerRepository;

        //After registeration, Injection occurs 
        public OrderController(IProductRepository productRepository,IOrderRepository order,ICustomerRepository customer)
        {
            this.productRepository=productRepository;
            orderRepository = order;
           customerRepository = customer;
        }
        public IActionResult Index()
        {
            Customer customer = customerRepository.getAddress(User.Identity.Name);
            List<Order> customerOrders = orderRepository.GetAllById(customer.Id);
            return View(customerOrders);
        }

        public IActionResult Detalis(int id)
        {
            return View(orderRepository.GetById(id));
        }

        [HttpGet]
        public IActionResult New()
        {
            OrderVM orderVM = new OrderVM();
            orderVM.Customer_Name = User.Identity.Name;
            orderVM.Order_Date=DateTime.Now;
            orderVM.Shipped_Date=orderVM.Order_Date.AddDays(7);
            Customer customer= customerRepository.getAddress(User.Identity.Name);
            orderVM.Address=customer.Address;
            List<int> Ids;
            if (Request.Cookies.ContainsKey("Ids") == true)
            {
                JavaScriptSerializer js = new JavaScriptSerializer();
                Ids = js.Deserialize<List<int>>(Request.Cookies["Ids"]);

            }
            else
            {
                Ids=new List<int>();
            }
            List<Product> products = new List<Product>();

            orderVM.products=productRepository.GetSelectedProducts(Ids);
            orderVM.Total_Price=orderVM.products.Select(p => p.Price).Sum();

           ViewData["Cust_List"]=customerRepository.GetAll();
            return View(orderVM);            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult New(Order order)
        {
            Customer customer = customerRepository.getAddress(User.Identity.Name);

            order.Customer_Id=customer.Id;
            orderRepository.Insert(order);

            //Empty Cart
            Response.Cookies.Append("Ids", JsonConvert.SerializeObject(new List<int>()));
           
            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewData["Cust_List"] = customerRepository.GetAll();
            Order order=orderRepository.GetById(id);
            return View(order);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id , Order order)
        {
            if (ModelState.IsValid)
            {
                orderRepository.Update(id, order);
                return RedirectToAction("Index");
            }
            
            ViewData["Cust_List"] = customerRepository.GetAll();
            return View(order);
        }

        public IActionResult Delete(int id)
        {
            orderRepository.Delete(id);
            return RedirectToAction("Index");
        }
        public IActionResult AdminView()
        {
            return View(orderRepository.GetAll());
        }

    }
}

MVC_Project/Controllers/ProductController.cs
using AutoMapper;
using Final_Project.Models;
using Final_Project.Repository;
using Final_Project.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Nancy.Json;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Final_Project.Controllers
{
    public class ProductController : Controller
    {
        private readonly IMapper mapper;
        IWebHostEnvironment webHostEnvironment;
        IProductRepository productRepository;

        public ProductController(IProductRepository product, IWebHostEnvironment webHostEnvironment)
        {
            productRepository = product;
            this.webHostEnvironment = webHostEnvironment;
            this.mapper = AutoMapperConfig.Mapper;

        }
        public IActionResult Index()
        {
            return View(productRepository.GetAll());
        }
       
        public IActionResult Details(int id)
        {
            return View(productRepository.GetById(id));
        }

        [HttpGet]
        public IActionResult New()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult New(ProductVM productVM)
        {
            if(productVM.ImageFile == null ||productVM.ImageFile.Length == 0) {
                ModelState.AddModelError("ImageFile","You Must Choose Image");
            }


            if (ModelState.IsValid)
            {
                Product product=mapper.Map<Product>(productVM);
                product.Image=uploadImage(productVM.ImageFile);

                productRepository.Insert(product);

                return RedirectToAction("AdminView");

            }
       
            return View(productVM);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Product product = productRepository.GetById(id);
            ProductVM productVM= mapper.Map<ProductVM>(product);
            return View(productVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id,ProductVM productVM)
        {
            if (ModelState.IsValid)
            {

                Product product = mapper.Map<Product>(productVM);
                if (productVM.ImageFile != null && productVM.ImageFile.Length != 0)
                {
                    product.Image=uploadImage(productVM.ImageFile, productVM.Image);
                }
                productRepository.Update(id, product);
                return RedirectToAction("AdminView");
            }

            return View(productVM);
        }

        public IActionResult Delete(int id)
        {
            productRepository.Delete(id);
            return RedirectToAction("AdminView");
        }
        
        public string uploadImage(IFormFile Image,string currentImage="")
        {
            

            string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "Images");

            string uniqueFileName = Guid.NewGuid().ToString() + "." + Path.GetExtension(Image.FileName);
            string filePath = Path.Combine(uploadsFolder, uniqueFileName);
            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                Image.CopyTo(fileStream);
                fileStream.Close();
            }

            //Delete Old Image
            if (!string.IsNullOrEmpty(currentImage))
            {
                string oldFilePath = Path.Combine(uploadsFolder, currentImage);
                System.IO.File.Delete(oldFilePath);
            }

            return uniqueFileName;
        }

        public IActionResult AdminView()
        {
            return View(productRepository.GetAll());
        }


        public IActionResult SetCookie(int id)
        {
            List<int>Ids;
            if (Request.Cookies.ContainsKey("Ids") == true)
            {
                JavaScriptSerializer js = new JavaScriptSerializer();
                 Ids = js.Deserialize< List<int> >(Request.Cookies["Ids"]);

            }
            else {
                Ids=new List<int>();      
            }
            Ids.Add(id);

            CookieOptions cookieOptions = new CookieOptions();
            cookieOptions.Expires = DateTimeOffset.Now.AddDays(3);


            Response.Cookies.Append("Ids", JsonConvert.SerializeObject(Ids), cookieOptions);
            if(Ids.Count()!=0)
                return Content(Ids.Count().ToString());
            else
                return Content("");
        }
        public IActionResult EmptyCart() {
            List<int> Ids=new List<int>();
            Response.Cookies.Append("Ids", JsonConvert.SerializeObject(Ids));
            return RedirectToAction("Index");
        }


    }
}

MVC_Project/Views/Shared/Footer.cshtml
<footer>
         <div class="container">
            <div class="row">
               <div class="col-md-4">
                   <div class="full">
                      <div class="logo_footer">
                        <a href="#"><img width="210" src="~/images/logo.png" alt="#" /></a>
                      </div>
                      <div class="information_f">
                        <p><strong>ADDRESS:</strong> ITI, Assiut</p>
                        <p><strong>TELEPHONE:</strong> +20 1234 456 789</p>
                        <p><strong>EMAIL:</strong> abc@gmail.com</p>
                      </div>
                   </div>
               </div>
               <div class="col-md-8">
                  <div class="row">
                  <div class="col-md-7">
                     <div class="row">
                        <div class="col-md-6">
                     <div class="widget_menu">
                        <h3>Menu</h3>
                        <ul>
                           <li><a asp-action="Index" asp-controller="Home">Home</a></li>
                           <li><a asp-action="Index" asp-controller="About">About</a></li>
                           <li><a asp-action="Index" asp-controller="Contact">Contact</a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6">
                     <div class="widget_menu">
                        <h3>Account</h3>
                        <ul>
                           
                           <li><a asp-action="Login" asp-controller="Account">Login</a></li>
                           <li><a asp-action="Register" asp-controller="Account">Register</a></li>
                           <li><a asp-action="Index" asp-controller="Product">Shopping</a></li>
                           
                        </ul>
                     </div>
                  </div>
                     </div>
                  </div>     
                  <div class="col-md-5">
                     <div class="widget_menu">
                        <h3>Newsletter</h3>
                        <div class="information_f">
                          <p>Subscribe by our newsletter and get update protidin.</p>
                        </div>
                        <div class="form_sub">
                           <form method="post">
                              <fieldset>
                                 <div class="field">
                                    <input type="email" placeholder="Enter Your Mail" required/>
                                    <input type="submit" value="Subscribe" />
                                 </div>
                              </fieldset>
                           </form>
                        </div>
                     </div>
                  </div>
                  </div>
               </div>
            </div>
         </div>
      </footer>
      <div class="cpy_">
         <p>© 2022 All Rights Reserved By MHM</p>
      </div>

MVC_Project/Views/Shared/NavBar.cshtml
 <header class="header_section">
      <div class="container">
         <nav class="navbar navbar-expand-lg custom_nav-container ">
            <a class="navbar-brand" href="home"><img width="250" src="~/images/logo.png" alt="#" /></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
               <ul class="navbar-nav">
                  <li class="nav-item">
                     <a class="nav-link" asp-action="Index" asp-controller="Home">Home <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item dropdown">
                     <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"> <span class="nav-label">Pages <span class="caret"></span></a>
                     <ul class="dropdown-menu">
                        <li><a asp-action="Index" asp-controller="About">About</a></li>
                        @if(@User.Identity.IsAuthenticated==false)
                        {
                        <li><a asp-action="Login"asp-controller="Account">Login</a></li>
                        <li><a asp-action="Register"asp-controller="Account">Register</a></li>
                        }
                        else{
                        <li><a asp-action="Index"asp-controller="Order">Orders</a></li>
                        <li><a asp-action="Logout"asp-controller="Account">Logout</a></li>
                        }
                    </ul>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" asp-action="Index" asp-controller="Product">Products</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" asp-action="Index" asp-controller="Contact">Contact</a>
                  </li>

                    <li class="nav-item">
                     <a class="nav-link" href="cart">
                       <i class="fa" style="font-size:24px">&#xf07a;</i>
                       <span class='badge badge-primary' id='lblCartCount'></span>
                     </a>
                  </li>
                    @if(@User.Identity.IsAuthenticated==true)
                    {
                      <li class="nav-item"><a class="nav-link">Welcome @User.Identity.Name </a></li>

                    }
               </ul>
            </div>
         </nav>
      </div>
   </header>

MVC_Project/Views/Shared/Product.cshtml
<style>
/* Popup container - can be anything you want */
a{
      cursor: pointer;
}
.popup {
  position: absolute;
  display:block;
  left: auto;
  right:auto;
  cursor: pointer;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}

/* The actual popup */
.popup .popuptext {
  visibility: hidden;
  width: 160px;
  background-color: #059862;
  color: #fff;
  text-align: center;
  border-radius: 6px;
  padding: 8px 0;
  position: fixed;
  bottom: 10%;
  left: 80%;
  z-index: 1;

  margin-left: -80px;
}

/* Popup arrow */
.popup .popuptext::after {
  content: "";
  position: absolute;
  left: auto;
  right:auto;
  margin-left: -5px;
  border-width: 5px;
  border-style: solid;
  border-color: #555 transparent transparent transparent;
}

/* Toggle this class - hide and show the popup */
.popup .show {
  visibility: visible;
  -webkit-animation: fadeIn 1s;
  animation: fadeIn 1s;
}

</style>
  
  <div class="popup">
  <span class="popuptext" id="myPopup"><span>&#10003;</span> Added To Cart</span>
</div>


 <section class="product_section layout_padding">
            
               <div class="heading_container" style="align-items: center;">
                  <h2>
                     Our <span>products</span>
                  </h2>
               </div>  
               <div class="row">
        @foreach (Product item in @Model)
        {
                  <div class="col-sm-6 col-md-4 col-lg-4">
                     <div class="box">
                        <div class="">
                           
                        </div>
                        <div  class="detail-box">
                            <h5  id="title1" >
                                @item.Name
                            </h5>
                            <h6 id="price1">
                              $ @item.Price
                            </h6>
                         </div>
                        <div class="img-box">
                           <img  id="img1"src="images/@item.Image" alt="">
                        </div>
                        <div class="option_container">
                            <div class="options">
        
                             <a class="option1" value="1" onclick="addProductToCart(@item.Id)">
                                Add to Cart
                                 </a>
     
                            </div>
                          
                        </div>
        
                        
                     </div>


                  </div>
        }               
                  </div>
                  @if( ViewData["Title"] == "Home Page"){
                  <div class="btn-box">
                     <a asp-action="Index" asp-controller="Product">
                        More products
                     </a>
                  </div>
                  }
         </section>
     <script>
       function myFunction() {
            var popup = document.getElementById("myPopup");
            popup.classList.add("show");
            setTimeout(function () {popup.classList.remove("show")}, 1000);	
        }
        function addProductToCart(id){ 
        
            var data = { id: id };
            $.ajax({
              type: "POST",
              url: 'Product/SetCookie/',
              data: data,
              success: function(resultData) {
                  myFunction();
                  document.getElementById("lblCartCount").innerText = resultData;
              }
            });
        }
        
    </script> 
@section Scripts {
      <script src="/js/product.js"></script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
 
}

MVC_Project/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en" class="">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Dashboard - Admin One Tailwind CSS Admin Dashboard</title>

  <!-- Tailwind is included -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <link rel="stylesheet" href="/css/main.css">

  <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png"/>
  <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png"/>
  <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png"/>
  <link rel="mask-icon" href="safari-pinned-tab.svg" color="#00b4b6"/>

  <meta name="description" content="Admin One - free Tailwind dashboard">

  <meta property="og:url" content="https://justboil.github.io/admin-one-tailwind/">
  <meta property="og:site_name" content="JustBoil.me">
  <meta property="og:title" content="Admin One HTML">
  <meta property="og:description" content="Admin One - free Tailwind dashboard">
  <meta property="og:image" content="https://justboil.me/images/one-tailwind/repository-preview-hi-res.png">
  <meta property="og:image:type" content="image/png">
  <meta property="og:image:width" content="1920">
  <meta property="og:image:height" content="960">

  <meta property="twitter:card" content="summary_large_image">
  <meta property="twitter:title" content="Admin One HTML">
  <meta property="twitter:description" content="Admin One - free Tailwind dashboard">
  <meta property="twitter:image:src" content="https://justboil.me/images/one-tailwind/repository-preview-hi-res.png">
  <meta property="twitter:image:width" content="1920">
  <meta property="twitter:image:height" content="960">

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-130795909-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-130795909-1');
  </script>

</head>
<body>

<div id="app">

  <nav class="navbar navbar-expand-lg custom_nav-container ">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
            </button>
            <div class="collapse navbar-collapse " id="navbarSupportedContent" style="width:100%">
               <ul class="navbar-nav row" style="width:100%"  >
                @if(@User.Identity.IsAuthenticated==true){
                    <li   class="nav-item text-end"><a >Welcome <b class="font-black" style="color:#1F2937">@User.Identity.Name</b> </a></li>
                }
              </ul>
            </div>
         </nav>
<aside class="aside is-placed-left is-expanded">
  <div class="aside-tools">
    <div>
       <b class="font-black">Admin</b>
    </div>
  </div>
  <div class="menu is-menu-main">
    <p class="menu-label">General</p>
    <ul class="menu-list">
      <li class="active">
        <a asp-action="" asp-controller="AdminDomain">
          <span class="icon"><i class="mdi mdi-desktop-mac"></i></span>
          <span class="menu-item-label">Dashboard</span>
        </a>
      </li>
    </ul>
    <p class="menu-label">Category</p>
    <ul class="menu-list">
      <li class="--set-active-tables-html">
        <a asp-action="AdminView" asp-controller="Customer">
          <span class="icon"><i class="mdi mdi-account-circle"></i></span>
          <span class="menu-item-label">Customers</span>
        </a>
      </li>
      <li class="--set-active-forms-html">
        <a asp-action="AdminView" asp-controller="Product">
          <span class="icon"><i class="mdi mdi-square-edit-outline"></i></span>
          <span class="menu-item-label">Products</span>
        </a>
      </li>
      <li class="--set-active-profile-html">
        <a asp-action="AdminView" asp-controller="Order">
          <span class="icon"><i class="mdi mdi-table"></i></span>
          <span class="menu-item-label">Orders</span>
        </a>
      </li>
      <li>
        <a asp-action="AdminLogout" asp-controller="Account">
          <span class="icon"><i class="mdi mdi-logout"></i></span>
          <span class="menu-item-label">Logout</span>
        </a>
      </li>
    </ul>
      </div>
</aside>





  <div class="container form">@RenderBody()</div>
<!-- Scripts below are for demo only -->
<script type="text/javascript" src="js/main.min.js?v=1628755089081"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
<script type="text/javascript" src="js/chart.sample.min.js"></script>


<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};
    if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
    n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t,s)}(window, document,'script',
    'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '658339141622648');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=658339141622648&ev=PageView&noscript=1"/></noscript>

<!-- Icons below are for demo only. Feel free to use any icon pack. Docs: https://bulma.io/documentation/elements/icon/ -->
<link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.9.95/css/materialdesignicons.min.css">
    @await RenderSectionAsync("Scripts", required: false) 

</body>
</html>

MVC_Project/Views/Shared/_NewLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>

        @RenderBody()
    </div>
    <!-- jQery -->
      <script src="~/js/jquery-3.4.1.min.js"></script>
      <!-- popper js -->
      <script src="~/js/popper.min.js"></script>
      <!-- bootstrap js -->
      <script src="~/js/bootstrap.js"></script>

      <!-- product js -->
      <script src="~/product.js"></script>
      <script src="~/./home.js"></script>
     @await RenderSectionAsync("Scripts", required: false) 

</body>
</html>